#!/bin/sh
#
# smallstache - logic-less template engine for shell.
# <https://github.com/macie/smallstache.sh>
#
# Copyright (c) 2023 Maciej Żok
# SPDX-License-Identifier: MIT


# following line is used by `make cli-release`
smallstache_version=24.1

case $# in
	0)
		echo 'smallstache: no template provided. See "smallstache -h" for help' >&2
		exit 64
		;;
	1)
		case $1 in
			-h|--help)
				cat >&2 <<-'EOF'
					smallstache - logic-less template engine for shell.

					Usage:
					   smallstache TEMPLATE_FILE
					   smallstache [-h | --help] [-v | --version]

					Options:
					   -h, --help             Show this help and exit.
					   -v, --version          Show version number and exit.

					Value from stdin KEY=VALUE pairs substitutes `{{KEY}}` in TEMPLATE_FILE.
					EOF
				exit 0
				;;
			-v|--version)
				printf 'smallstache %s\n' "${smallstache_version}" >&2
				exit 0
				;;
			*)
				if [ ! -s "$1" ]; then
					printf 'smallstache: file %s is empty' "$1" >&2
					exit 64
				fi
				;;
		esac
		;;
	2)
		echo 'smallstache: too many arguments. See "smallstache -h" for help' >&2
		exit 64
		;;
esac

# transform each stdin line in form `KEY=VALUE` into `s|{{ *KEY *}}|VALUE|g; `
smallstache_regex=$(sed 's_\([^=]*\)=\(.*\)_s|{{ *\1 *}}|\2|g; _g')
sed -e "${smallstache_regex}" "$1"
